services:
  postgres:
    restart: always
  web:
    command: dotenvx run -f .env.production -- npm run start
    build:
      dockerfile: Dockerfile
      target: build
      args:
        ENV_FILE: '.env.production'
    ports:
      - '3000:3000'
    restart: always
    environment:
      DOTENV_PRIVATE_KEY_PRODUCTION: ${DOTENV_PRIVATE_KEY_PRODUCTION}
