services:
  web:
    ports:
      - '3000:3000'
      - '24678:24678'
    command:
      [
        'nodemon',
        '--signal',
        'SIGINT',
        'src/server/main.ts',
        '-w',
        'src/server'
      ]
    init: true
    develop:
      watch:
        - path: ./src
          action: sync
          target: /app/src
        - path: package.json
          action: rebuild
        - path: Dockerfile
          action: rebuild
        - path: compose.yaml
          action: rebuild
        - path: compose.override.yaml
          action: rebuild
