services:
  web:
    build:
      dockerfile: Dockerfile
      target: build
    ports:
      - '3000:3000'
    environment:
      VITE_BASE_URL: 'http://localhost:3000'
      VITE_MAPS_API_KEY: 'AIzaSyBsSN0chGU2krx7HNvJTh6g0v3502TsByo'
      DOTENV_KEY: 'dotenv://:key_3140a1b2b37abf2d65b40c6d70906f801587662b228f17aa89506f539bd20aa3@dotenv.org/vault/.env.vault?environment=production'
