services:
  postgres:
    image: 'postgis/postgis:15-3.4'
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    secrets: &db_secrets
      - db_password
    environment: &db_env
      POSTGRES_DB: tcmmap
      POSTGRES_USER: tcmmap
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
  web:
    build:
      dockerfile: Dockerfile
      target: development
      args:
        ENV_FILE: '.env'
        SRC_ENVS: ${SRC_ENVS}
    depends_on:
      - postgres
    secrets: *db_secrets
    environment:
      <<: *db_env
      PGHOST: postgres

secrets:
  db_password:
    file: .secrets/db_password.txt

volumes:
  db_data:
