export const countyLabels: { [k: string]: string } = {};

export const counties = [
	'Santa Clara County',
	'San Mateo County',
	'Alameda County',
	'Orange County',
	'Los Angeles County',
	'Sacramento County',
	'Santa Cruz County',
	'San Diego County',
	'Merced County',
	'Santa Barbara County',
	'Contra Costa County',
	'San Joaquin County',
	'Kern County',
	'San Luis Obispo County',
	'Fresno County',
	'Monterey County',
	'Nevada County',
	'Riverside County',
	'Placer County',
	'Unknown',
	'San Bernardino County',
	'Tuolumne County',
	'Sonoma County',
	'San Francisco County',
	'Shasta County',
	'Sutter County',
	'Plumas County',
	'Humboldt County',
	'Yolo County',
	'Marin County',
	'Stanislaus County',
	'Tulare County',
	'Ventura County',
	'Out of State',
	'Mendocino County',
	'Napa County',
	'Siskiyou County',
	'Butte County',
	'Madera County',
	'Imperial County',
	'Kings County',
	'El Dorado County',
	'Solano County',
	'Calaveras County',
	'San Benito County',
	'Amador County',
	'Yuba County',
	'Colusa County',
	'Del Norte County',
	'Mono County',
	'Tehama County',
	'Trinity County',
	'Glenn County',
	'Lake County',
	'Sierra County',
	'Mariposa County',
	'Modoc County',
	'Inyo County',
	'Lassen County',
	'Alpine County'
];
