export const industryLabels: { [k: string]: string } = {
	'Government & Public Sector': 'Government',
	'Faith-based Groups': 'Faith-Based',
	'Immigrant Rights and/or Services': 'Immigrant Rights',
	'Community Service & Organizing': 'Community Service',
	'Nutrition & Food Security': 'Nutrition',
	'Youth Engagement & Services': 'Youth Engagement',
	'LGBTQ+ Rights and/or Services': 'LGBTQ+ Rights',
	'Civil Rights & Equity': 'Civil Rights',
	'Disability Rights and/or Services': 'Disability Rights'
};

export const industries = [
	'Government & Public Sector',
	'Philanthropy',
	'Other',
	'Faith-based Groups',
	'Early Childhood',
	'Recreation',
	'Immigrant Rights and/or Services',
	'Group Engagement',
	'Animal Rights',
	'Education',
	'Parent Groups',
	'Environment',
	'Trauma & Resilience',
	'Child Welfare',
	'Labor',
	'Health',
	'Community Service & Organizing',
	'Legal Services',
	'STEM',
	'Arts',
	'Media',
	'Business',
	'Nutrition & Food Security',
	'Youth Engagement & Services',
	'LGBTQ+ Rights and/or Services',
	'Family Support',
	'Civil Rights & Equity',
	'Museums',
	'Economic Security',
	'Disability Rights and/or Services',
	'Oral Health'
];
